### ISSUE TITLE
Cannot find module "boring-router" when using workspaces

### ISSUE THREAD

**Issue by mikecann** [makeflow/boring-router#116]
![image](https://github.com/mufancom/boring-router/assets/215033/088c37f8-1305-4a34-a6a8-36d20e328902)

Im using yarn workspaces (yarn version 3.2.2) and adding `boring-router` and `boring-router-react` to one of my workspace projects in the mono-repo. 

Unfortunately typescript is unable to find the module. 

This is strange as the modules have been installed in `node_modules` they just get hoisted up to the top level as usual: 

![image](https://github.com/mufancom/boring-router/assets/215033/be315ce1-9914-4643-916f-837042c47e30)

But for some reason the project cannot find them.

Do you know why this is? I dont seem to have any issues with any other dependencies.

**Comment by vilic** [comment]
That's interesting, and yarn has v3 now? I'll test it in minutes.

**Comment by mikecann** [comment]
yep, tho I dont think its a v3 specific issue just a worspaces issue, you would probably have the same problem with earlier versions or npm workspaces

**Comment by vilic** [comment]
I currently use yarn v1 (hoisted up) and pnpm (not hoisted), and they both seem to work. Does the color in the module list mean anything?

**Comment by mikecann** [comment]
Here is the example repo showing the issue: https://github.com/mikecann/boring-example

Not sure, there are other directories colored the same: 

![image](https://github.com/mufancom/boring-router/assets/215033/3c30c509-3800-4b4a-a7fb-bc995832da4b)

**Comment by vilic** [comment]
I guess it's something related to yarn pnp, trying to find a fix.

**Comment by mikecann** [comment]
ye its odd as no other repo has the issue.. might be worth looking at the differences in the package.json between boring and others?

**Comment by vilic** [comment]
@mikecann That would surprise me as `exports` is now wildly adopted. But maybe because it's missing the `default` export. I'll try to add that. But if that doesn't work, I'll have to come back later for this problem.

**Comment by mikecann** [comment]
okay thanks

**Comment by vilic** [comment]
@mikecann Welcome but unfortunately not working. Will investigate this evening.

**Comment by mikecann** [comment]
okay no worries, I eagerly await your investigations. I have used boring in the past and have really enjoyed it, would love to get it going again.

**Comment by vilicvane** [comment]
@mikecann Okay actually you are right, I added `main` and `types` and it's working now (try `0.5.21-alpha.1`). (I feel blessed never upgraded to yarn 2+.)

I still use it in my latest projects but don't get much time promote it. Any other issue please let me know. ;)

**Comment by mikecann** [comment]
wooo nice! thats seems to have it :)

**Comment by boenfu** [comment]
> That's interesting, and yarn has v3 now? I'll test it in minutes.

yarn 4 was released three days ago 😝

**Comment by Yggdrasilqh** [comment]
> Here is the example repo showing the issue: https://github.com/mikecann/boring-example
> 
> Not sure, there are other directories colored the same:
> 
> ![image](https://user-images.githubusercontent.com/215033/278218715-3c30c509-3800-4b4a-a7fb-bc995832da4b.png)

Based on the example project you provided, there might be another possible solution. The main cause of this issue is likely the `moduleResolution` configuration in the `tsconfig.json` file. If it is configured as `node`, it will not recognize the exports configuration in the `package.json`.

[check this](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node)

<img width="986" alt="image" src="https://github.com/mufancom/boring-router/assets/18239773/7aeb9ffa-85fa-427f-9183-d5f55bd38550">
